#### 算数运算和数据对齐

In [42]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [43]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [44]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [45]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [46]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [47]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [48]:
df1 = DataFrame(np.arange(9).reshape((3, 3)), columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

In [49]:
df2 = DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [50]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [51]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [52]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

####  在算数方法中填充值

In [53]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [54]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [55]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [56]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [57]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [58]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [59]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### DataFrame 和 Series 之间的运算

In [60]:
arr = np.arange(12.).reshape((3, 4))

In [61]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [62]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [63]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [64]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [65]:
series = frame.ix[0]

In [66]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [67]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [68]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [69]:
series2 = Series(range(3), index=['b', 'e', 'f'])

In [70]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [71]:
series2

b    0
e    1
f    2
dtype: int64

In [72]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [73]:
series3 = frame['d']

In [75]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [76]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [77]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用和映射

In [78]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [79]:
frame

b         d         e
Utah   -0.035513 -0.915422 -1.152536
Ohio   -0.817869  0.091871 -1.365822
Texas  -1.356286 -0.004184  0.549092
Oregon  0.968116 -0.186285 -0.900865

In [80]:
np.abs(frame)

b         d         e
Utah    0.035513  0.915422  1.152536
Ohio    0.817869  0.091871  1.365822
Texas   1.356286  0.004184  0.549092
Oregon  0.968116  0.186285  0.900865

In [81]:
frame

b         d         e
Utah   -0.035513 -0.915422 -1.152536
Ohio   -0.817869  0.091871 -1.365822
Texas  -1.356286 -0.004184  0.549092
Oregon  0.968116 -0.186285 -0.900865

In [82]:
frame.abs()

b         d         e
Utah    0.035513  0.915422  1.152536
Ohio    0.817869  0.091871  1.365822
Texas   1.356286  0.004184  0.549092
Oregon  0.968116  0.186285  0.900865

In [83]:
f = lambda x: x.max() - x.min()

In [84]:
f

<function __main__.<lambda>>

In [85]:
frame

b         d         e
Utah   -0.035513 -0.915422 -1.152536
Ohio   -0.817869  0.091871 -1.365822
Texas  -1.356286 -0.004184  0.549092
Oregon  0.968116 -0.186285 -0.900865

In [86]:
frame.apply(f)
# axis=0 应用于行；axis=1 应用于列

b    2.324402
d    1.007292
e    1.914914
dtype: float64

In [87]:
frame.apply(f, axis=1)

Utah      1.117023
Ohio      1.457693
Texas     1.905378
Oregon    1.868981
dtype: float64

In [88]:
frame.apply(f, axis=0)

b    2.324402
d    1.007292
e    1.914914
dtype: float64

In [92]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [93]:
frame

b         d         e
Utah   -0.035513 -0.915422 -1.152536
Ohio   -0.817869  0.091871 -1.365822
Texas  -1.356286 -0.004184  0.549092
Oregon  0.968116 -0.186285 -0.900865

In [94]:
frame.apply(f)

b         d         e
min -1.356286 -0.915422 -1.365822
max  0.968116  0.091871  0.549092

In [95]:
format = lambda x: '%.2f' % x

In [96]:
frame.applymap(format)

b      d      e
Utah    -0.04  -0.92  -1.15
Ohio    -0.82   0.09  -1.37
Texas   -1.36  -0.00   0.55
Oregon   0.97  -0.19  -0.90

In [97]:
frame['e'].map(format)

Utah      -1.15
Ohio      -1.37
Texas      0.55
Oregon    -0.90
Name: e, dtype: object

### 排序和排名

In [98]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])

In [99]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [101]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [102]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                 columns=['d', 'a', 'b', 'c'])

In [103]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [104]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [105]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [107]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [108]:
obj = Series([4, 7, -3, 2])

In [110]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [111]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])

In [112]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [113]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [115]:
Series.sort_values(obj)

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [117]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [118]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [120]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [122]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [123]:
obj = Series([7, -5, 7, 4, 2, 0, 4])

In [124]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [125]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [126]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [127]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [128]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [129]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                  'c': [-2, 5, 8, -2.5]})

In [130]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [131]:
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

#### 带有重复值的轴索引

In [132]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [133]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [134]:
obj.index.is_unique

False

In [136]:
obj['a']

a    0
a    1
dtype: int64

In [137]:
obj['c']

4

In [139]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [140]:
df 

0         1         2
a  2.093450 -0.017984  1.651371
a  0.319082  0.176898  1.269781
b -1.362920 -0.579794  1.106862
b  0.128444 -1.669626 -0.563058

In [142]:
df.ix['b']

0         1         2
b -1.362920 -0.579794  1.106862
b  0.128444 -1.669626 -0.563058

### 汇总和计算描述统计

In [143]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
               [np.nan, np.nan], [0.75, -1.3]],
              index=['a', 'b', 'c', 'd'],
              columns=['one', 'two'])

In [144]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [145]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [147]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [148]:
df.mean(axis=1, skipna=False)
# axis: DataFrame 的行用 0，列用 1

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [149]:
df.idxmax()

one    b
two    d
dtype: object

In [150]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [151]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [152]:
obj = Series(['a', 'b', 'c', 'd'] * 4)

In [153]:
obj

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
dtype: object

In [154]:
obj.describe()

count     16
unique     4
top        a
freq       4
dtype: object

In [155]:
df.count()

one    3
two    2
dtype: int64

In [156]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [157]:
df.count(axis=1)

a    1
b    2
c    0
d    2
dtype: int64