In [2]:
import numpy as np

In [3]:
arr = np.random.randn(4, 4)

In [4]:
arr

array([[ 1.70548347,  0.25539722,  2.17597794, -1.63069764],
       [ 0.37110387,  0.03955814,  1.30398945,  1.1423734 ],
       [ 0.07472211,  1.78800676,  0.25297093,  0.43440928],
       [ 0.3882529 ,  0.66647998,  0.14750999,  0.68353844]])

In [5]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2, -2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [6]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -1.63069764],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

### 数学和统计方法

In [7]:
arr = np.random.randn(4, 4)

In [8]:
arr

array([[ 0.08515283, -0.99688936,  0.10936469,  0.19799953],
       [-1.20856435, -0.86098851,  1.17413421, -1.8086723 ],
       [ 1.35789708,  0.3917919 , -0.6463659 , -1.11416341],
       [ 0.91994368, -0.13051688,  0.8575389 ,  0.37672797]])

In [9]:
arr.mean()

-0.080975619534318255

In [10]:
np.mean(arr)

-0.080975619534318255

In [11]:
arr.sum()

-1.2956099125490921

In [12]:
arr = np.ones((3, 4))

In [13]:
arr

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
arr[0] = 0

In [16]:
arr[2] = 2

In [17]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.]])

In [18]:
arr.mean(axis=1)
# 纵轴均值

array([ 0.,  1.,  2.])

In [19]:
arr.mean(axis=0)
# 横轴均值

array([ 1.,  1.,  1.,  1.])

In [21]:
arr.mean(axis=-1)

array([ 0.,  1.,  2.])

In [22]:
arr.sum(0)
# 纵轴总和

array([ 3.,  3.,  3.,  3.])

In [23]:
arr.sum(1)
# 横轴总和

array([ 0.,  4.,  8.])

In [25]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [26]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [27]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [28]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr = np.random.randn(100)

In [31]:
(arr > 0).sum()

60

In [32]:
bools = np.array([False, False, True, False])

In [33]:
bools.any()

True

In [34]:
bools.all()

False

In [35]:
np.any(bools)

True

In [36]:
np.all(bools)

False

## 排序

In [38]:
arr = np.random.randn(8)

In [39]:
arr

array([  5.35689467e-01,   2.04695857e-01,   2.19204608e-01,
         3.06991679e-04,   5.94163839e-01,   5.68163130e-01,
        -1.14084145e-01,   3.06093198e-01])

In [40]:
arr.sort()

In [41]:
arr

array([ -1.14084145e-01,   3.06991679e-04,   2.04695857e-01,
         2.19204608e-01,   3.06093198e-01,   5.35689467e-01,
         5.68163130e-01,   5.94163839e-01])

In [42]:
arr = np.random.randn(5, 3)

In [43]:
arr

array([[ 2.03546994,  1.19845092, -2.25625468],
       [-0.19073556, -1.18478008,  0.45703037],
       [ 1.26821575,  0.9084357 ,  2.60790437],
       [-1.25374546, -0.42519276,  0.45350698],
       [ 2.37711465,  1.80094508, -0.0740709 ]])