# 1 Probability and Statistics  
## (1) (combinatorics)  

In [1]:
def C(N, K):
    if (K == 0) or (K == N):
        result = 1
        return result
    else:
        result = C(N - 1, K) + C(N - 1, K - 1)
        return result

## (2) (counting)

In [2]:
C(10, 4) / (2 ** 10)

0.205078125

In [3]:
(C(4, 3) * 13 * C(4, 2) * 12) / (C(52, 5))

0.0014405762304921968

## (3) (conditional probability)

In [4]:
p = 1 / 2
p ** 3 / (1 - p **  3)

0.14285714285714285

## (4) (Bayes theorem)

    P(X < 0 | |X| = 1)  
    = P(X = - 1 | |X| = 1)  
    = (P(|X| = 1 | X = - 1) * P(X = - 1)) / P(B)  
    = P(X = - 1) / P(|X| = 1)  
    = ((1 / 2) * (1 / 4)) / ((1 / 2) * (1 / 8) + (1 / 2) * (1 / 4))  
    = 2 / 3

## (5) (union/intersection)

    max P(A ∩ B) = min {P(A), P(B)} = 0.3  
    min P(A ∩ B) = max {0, P(A) + P(B) - 1} = 0  
    max P(A ∪ B) = min {1, P(A) + P(B)} = 0.7  
    min P(A ∪ B) = max {P(A), P(B)} = 0.4   

# 2 Linear Algebra

## (1) (rank)

In [5]:
import numpy as np

In [6]:
A = np.array([[1, 2, 1],
              [1, 0, 3],
              [1, 1, 2]])
np.linalg.matrix_rank(A)

2

## (2) (inverse)

In [7]:
A = np.array([[0, 2, 4],
              [2, 4, 2],
              [3, 3, 1]])
np.linalg.inv(A)

array([[ 0.125, -0.625,  0.75 ],
       [-0.25 ,  0.75 , -0.5  ],
       [ 0.375, -0.375,  0.25 ]])

## (3) (eigenvalues/eigenvectors)

In [8]:
A = np.array([[3, 1, 1],
              [2, 4, 2], 
              [-1, -1, 1]])

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [10]:
eigenvalues

array([ 4. +0.00000000e+00j,  2. +4.44089210e-16j,  2. -4.44089210e-16j])

In [11]:
eigenvectors

array([[-0.40824829+0.j        , -0.42295663+0.35410429j,
        -0.42295663-0.35410429j],
       [-0.81649658+0.j        , -0.27886944-0.35410429j,
        -0.27886944+0.35410429j],
       [ 0.40824829+0.j        ,  0.70182607+0.j        ,  0.70182607-0.j        ]])

## (4) (singular value decomposition)

奇异值分解

## (5) (PD/PSD)

## (6) (inner product)

# 3 Calculus

## (1) (differential and partial differential)

In [29]:
import numpy as np
import sympy as sp
x = sp.Symbol('x')
sp.diff(sp.log(1 + np.e ** ((-2) * x)), x)

-2.0*2.71828182845905**(-2*x)/(1 + 2.71828182845905**(-2*x))

In [31]:
x = sp.Symbol('x')
y = sp.Symbol('y')
sp.diff(np.e ** x + np.e ** (2 * y) + np.e ** (3 * x * y ** 2), y)

2.0*2.71828182845905**(2*y) + 6.0*2.71828182845905**(3*x*y**2)*x*y

## (2) (chain rule)

In [ ]:
x = sp.Symbol('x')
y = sp.Symbol('y')
x = sp.Symbol('x')
y = sp.Symbol('y')