# 数据转换
## 移除重复数据

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                'k2': [1, 1, 2, 3, 3, 4, 4]})

In [3]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [4]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [5]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [6]:
data['va'] = range(7)

In [7]:
data

k1  k2  va
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [8]:
data.drop_duplicates(['k1'])

k1  k2  va
0  one   1   0
3  two   3   3

In [9]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  va
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

In [10]:
help(data.drop_duplicates)

Help on method drop_duplicates in module pandas.core.frame:

drop_duplicates(subset=None, keep='first', inplace=False) method of pandas.core.frame.DataFrame instance
    Return DataFrame with duplicate rows removed, optionally only
    considering certain columns
    
    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns
    keep : {'first', 'last', False}, default 'first'
        - ``first`` : Drop duplicates except for the first occurrence.
        - ``last`` : Drop duplicates except for the last occurrence.
        - False : Drop all duplicates.
    take_last : deprecated
    inplace : boolean, default False
        Whether to drop duplicates in place or to return a copy
    
    Returns
    -------
    deduplicated : DataFrame



In [11]:
data.drop_duplicates(['k1', 'k2'], keep=False)

k1  k2  va
2  one   2   2

In [12]:
data

k1  k2  va
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

## 利用函数或映射进行数据转换

In [13]:
data = DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
                          'forned beef', 'Bacon', 'pastrami', 'honey ham',
                          'nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [14]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  forned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [15]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'cow',
    'pastrami': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [16]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [17]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     cow
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  forned beef     7.5     NaN
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [18]:
data['food'].map(lambda x: meat_to_animal[x.lower()])
# why？

KeyError: 'forned beef'

## 替换值

In [19]:
data = Series([1., -999., 2., -999., -1000., 3.])

In [20]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [23]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [24]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 重命名轴索引

In [25]:
data = DataFrame(np.arange(12).reshape((3, 4)),
                index=['Ohio', 'Colorado', 'New York'],
                columns=['one', 'two', 'three', 'four'])

In [26]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [27]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [28]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [29]:
data.index = data.index.map(str.upper)

In [30]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [31]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [32]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [33]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [34]:
_ = data.rename(index={'OHIO': 'INDIANA'},
               inplace=True)

In [35]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

## 离散化和面元划分

In [36]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [37]:
bins = [18, 25, 35, 60, 100]

In [38]:
cats = pd.cut(ages, bins)

In [39]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [40]:
type(cats)

pandas.core.categorical.Categorical

In [41]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [42]:
help(cats)

Help on Categorical in module pandas.core.categorical object:

class Categorical(pandas.core.base.PandasObject)
 |  Represents a categorical variable in classic R / S-plus fashion
 |  
 |  `Categoricals` can only take on only a limited, and usually fixed, number
 |  of possible values (`categories`). In contrast to statistical categorical
 |  variables, a `Categorical` might have an order, but numerical operations
 |  (additions, divisions, ...) are not possible.
 |  
 |  All values of the `Categorical` are either in `categories` or `np.nan`.
 |  Assigning values outside of `categories` will raise a `ValueError`. Order
 |  is defined by the order of the `categories`, not lexical order of the
 |  values.
 |  
 |  Parameters
 |  ----------
 |  values : list-like
 |      The values of the categorical. If categories are given, values not in
 |      categories will be replaced with NaN.
 |  categories : Index-like (unique), optional
 |      The unique categories for this categorical. If not

In [43]:
cats.categories

Index(['(18, 25]', '(25, 35]', '(35, 60]', '(60, 100]'], dtype='object')

In [44]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [45]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [46]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [47]:
help(pd.cut)

Help on function cut in module pandas.tools.tile:

cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False)
    Return indices of half-open bins to which each value of `x` belongs.
    
    Parameters
    ----------
    x : array-like
        Input array to be binned. It has to be 1-dimensional.
    bins : int or sequence of scalars
        If `bins` is an int, it defines the number of equal-width bins in the
        range of `x`. However, in this case, the range of `x` is extended
        by .1% on each side to include the min or max values of `x`. If
        `bins` is a sequence it defines the bin edges allowing for
        non-uniform bin width. No extension of the range of `x` is done in
        this case.
    right : bool, optional
        Indicates whether the bins include the rightmost edge or not. If
        right == True (the default), then the bins [1,2,3,4] indicate
        (1,2], (2,3], (3,4].
    labels : array or boolean, default None
      

In [48]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [49]:
pd.cut(ages, bins, labels=group_names).categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [50]:
data = np.random.randn(20)

In [51]:
data

array([ 0.83042788, -0.48458705, -0.37026972, -0.41067349, -0.91805844,
       -0.31741007,  0.75624224,  0.21161365, -0.27058642,  0.00243886,
        0.41618919, -0.62945769, -0.0737003 ,  1.24209291, -0.51007589,
        1.62456103,  1.82728425,  1.23777719, -0.22557087,  2.28934113])

In [52]:
pd.cut(data, 4, precision=2)

[(0.69, 1.49], (-0.92, -0.12], (-0.92, -0.12], (-0.92, -0.12], (-0.92, -0.12], ..., (1.49, 2.29], (1.49, 2.29], (0.69, 1.49], (-0.92, -0.12], (1.49, 2.29]]
Length: 20
Categories (4, object): [(-0.92, -0.12] < (-0.12, 0.69] < (0.69, 1.49] < (1.49, 2.29]]

In [53]:
data = np.random.randn(1000)

In [54]:
cats = pd.qcut(data, 4)

In [55]:
cats

[[-4.32, -0.685], [-4.32, -0.685], [-4.32, -0.685], (0.636, 3.0718], (-0.685, -0.0453], ..., (-0.0453, 0.636], (-0.0453, 0.636], [-4.32, -0.685], (0.636, 3.0718], (-0.685, -0.0453]]
Length: 1000
Categories (4, object): [[-4.32, -0.685] < (-0.685, -0.0453] < (-0.0453, 0.636] < (0.636, 3.0718]]

In [56]:
pd.value_counts(cats)

(0.636, 3.0718]      250
(-0.0453, 0.636]     250
(-0.685, -0.0453]    250
[-4.32, -0.685]      250
dtype: int64

In [57]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.282, -0.0453], (-1.282, -0.0453], [-4.32, -1.282], (-0.0453, 1.28], (-1.282, -0.0453], ..., (-0.0453, 1.28], (-0.0453, 1.28], (-1.282, -0.0453], (-0.0453, 1.28], (-1.282, -0.0453]]
Length: 1000
Categories (4, object): [[-4.32, -1.282] < (-1.282, -0.0453] < (-0.0453, 1.28] < (1.28, 3.0718]]

## 检测和过滤异常值

In [58]:
np.random.seed(12345)

In [59]:
data = DataFrame(np.random.randn(1000, 4))

In [60]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [61]:
data

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [62]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [63]:
col = data[3]

In [64]:
col

0     -0.555730
1      0.281746
2     -1.296221
3      0.886429
4     -0.438570
5     -1.021228
6      0.523772
7     -0.831154
8      0.560145
9      0.332883
10    -0.970736
11    -0.753887
12     0.246674
13    -0.919262
14    -0.660524
15     0.670216
16    -2.304234
17     1.074623
18    -0.503087
19     0.222896
20     0.433610
21     0.850591
22     2.169461
23     0.795253
24     0.152677
25    -0.929006
26     0.980928
27     0.457002
28    -0.402827
29    -1.648985
         ...   
970   -1.460094
971    0.132262
972   -1.091849
973   -1.243078
974   -0.521155
975   -0.307670
976    1.381155
977    0.075798
978    0.102469
979    1.120895
980   -0.285176
981    0.053410
982    0.233619
983    0.604880
984   -0.335099
985    1.367213
986   -0.512542
987   -1.050942
988   -0.387002
989    1.642339
990    1.336648
991    0.153988
992   -1.466596
993    1.101972
994    0.604072
995    1.653126
996   -1.502870
997    0.133304
998   -0.303340
999    0.882755
Name: 3, dtype: float64

In [65]:
col[np.abs(col) > 3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [66]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [67]:
(np.abs(data) > 3).any()

0    True
1    True
2    True
3    True
dtype: bool

In [68]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [69]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

## 排列和随机采样

In [70]:
 df = DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [71]:
sampler = np.random.permutation(5)

In [72]:
sampler

array([1, 0, 2, 3, 4])

In [73]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [75]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [78]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [79]:
bag = np.array([5, 7, -1, 6, 4])

In [80]:
sampler = np.random.randint(0, len(bag), size=10)

In [81]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [83]:
draws = bag.take(sampler)

In [84]:
draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

## 计算指标、哑变量

In [85]:
df = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
               'data1': range(6)})

In [86]:
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [89]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [90]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [91]:
df_with_dummy = df[['data1']].join(dummies)

In [93]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [98]:
mnames = ['movie_id', 'title', 'genres']

In [100]:
movies = pd.read_table('/Users/wonderful/Documents/技术书籍/Data_Analysis_and_Finance_文件集合/Python_for_Data_Analysis/pydata-book-master/ch02/movielens/movies.dat',
                      sep='::',
                      header=None,
                      names=mnames,
                      engine='python')

In [102]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [108]:
genre_iter = (set(x.split('|')) for x in movies.genres)

In [109]:
genres = sorted(set.union(*genre_iter))

In [114]:
dummies = DataFrame(np.zeros((len(movies), len(genres))), columns=genres)

In [115]:
for i, gen in enumerate(movies.genres):
    dummies.ix[i, gen.split('|')] = 1

In [116]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [118]:
movies_windic.ix[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [119]:
values = np.random.randn(10)

In [120]:
values

array([ 0.32496836,  0.20377461,  0.34886204,  0.51600937, -0.48982135,
       -0.6287463 ,  0.2664145 ,  1.0836849 ,  0.30334881, -1.1072385 ])

In [121]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [123]:
pd.get_dummies(pd.cut(values, bins))

(0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1]
0         0           1           0           0         0
1         0           1           0           0         0
2         0           1           0           0         0
3         0           0           1           0         0
4         0           0           0           0         0
5         0           0           0           0         0
6         0           1           0           0         0
7         0           0           0           0         0
8         0           1           0           0         0
9         0           0           0           0         0