# ufunc 高级应用

## ufunc 实例方法

In [3]:
import numpy as np
from numpy.random import randn

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.add.reduce(arr)

45

In [7]:
sum(arr)

45

In [8]:
arr.sum()

45

In [10]:
arr = randn(5, 5)

In [11]:
arr

array([[-1.52544981,  0.26675464,  0.95911079, -0.86129637,  0.02065652],
       [-0.67516472, -0.26134556, -1.41667888, -1.37588396, -0.19986079],
       [-0.94939444,  0.44924248,  0.33412529,  0.19389574,  1.99812734],
       [-1.18860064,  0.2036572 ,  1.09026388, -0.44300542, -0.58308839],
       [-0.33902892, -0.16305914,  1.48911712, -0.55409005, -1.04307996]])

In [12]:
arr[::2].sort(1)

In [13]:
arr

array([[-1.52544981, -0.86129637,  0.02065652,  0.26675464,  0.95911079],
       [-0.67516472, -0.26134556, -1.41667888, -1.37588396, -0.19986079],
       [-0.94939444,  0.19389574,  0.33412529,  0.44924248,  1.99812734],
       [-1.18860064,  0.2036572 ,  1.09026388, -0.44300542, -0.58308839],
       [-1.04307996, -0.55409005, -0.33902892, -0.16305914,  1.48911712]])

In [14]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True]], dtype=bool)

In [15]:
arr[:, :-1]

array([[-1.52544981, -0.86129637,  0.02065652,  0.26675464],
       [-0.67516472, -0.26134556, -1.41667888, -1.37588396],
       [-0.94939444,  0.19389574,  0.33412529,  0.44924248],
       [-1.18860064,  0.2036572 ,  1.09026388, -0.44300542],
       [-1.04307996, -0.55409005, -0.33902892, -0.16305914]])

In [16]:
arr

array([[-1.52544981, -0.86129637,  0.02065652,  0.26675464,  0.95911079],
       [-0.67516472, -0.26134556, -1.41667888, -1.37588396, -0.19986079],
       [-0.94939444,  0.19389574,  0.33412529,  0.44924248,  1.99812734],
       [-1.18860064,  0.2036572 ,  1.09026388, -0.44300542, -0.58308839],
       [-1.04307996, -0.55409005, -0.33902892, -0.16305914,  1.48911712]])

In [17]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [18]:
arr = np.arange(15).reshape((3, -1))

In [19]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [21]:
arr = np.arange(3).repeat([1, 2, 2])

In [22]:
arr

array([0, 1, 1, 2, 2])

In [23]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [25]:
result = np.subtract.outer(randn(3, 4), randn(5))

In [26]:
result

array([[[-0.18405469, -1.01828629, -1.42932907, -0.70399261, -1.32718368],
        [ 1.85028917,  1.01605757,  0.60501479,  1.33035126,  0.70716019],
        [ 2.06862726,  1.23439566,  0.82335288,  1.54868935,  0.92549828],
        [ 0.50713593, -0.32709567, -0.73813846, -0.01280199, -0.63599306]],

       [[ 0.73928975, -0.09494185, -0.50598463,  0.21935183, -0.40383924],
        [-0.41593917, -1.25017077, -1.66121356, -0.93587709, -1.55906816],
        [ 0.17742874, -0.65680286, -1.06784564, -0.34250917, -0.96570024],
        [ 2.69946444,  1.86523283,  1.45419005,  2.17952652,  1.55633545]],

       [[-0.56133365, -1.39556525, -1.80660803, -1.08127157, -1.70446264],
        [ 1.05643394,  0.22220234, -0.18884044,  0.53649602, -0.08669505],
        [-0.16209163, -0.99632323, -1.40736602, -0.68202955, -1.30522062],
        [ 0.21549327, -0.61873833, -1.02978111, -0.30444464, -0.92763571]]])

In [27]:
result.shape

(3, 4, 5)

In [28]:
arr = np.arange(10)

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [35]:
np.arange(4)

array([0, 1, 2, 3])

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
arr = np.multiply.outer(np.arange(4), np.arange(5))

In [37]:
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

## 自定义 ufunc

In [38]:
def add_elements(x, y):
    return x + y

In [39]:
add_them = np.frompyfunc(add_elements, 2, 1)

In [40]:
add_them(1, 2)

3

In [42]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [43]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
add__them = np.vectorize(add_elements, otypes=[np.float64])

In [46]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [47]:
arr = randn(10000)

In [48]:
%timeit add_them(arr, arr)

100 loops, best of 3: 1.97 ms per loop


In [49]:
%timeit np.add(arr, arr)

The slowest run took 44.57 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.46 µs per loop


# 结构化和记录式数组

In [52]:
dtype = [('x', np.float64), ('y', np.int32)]

In [53]:
dtype

[('x', numpy.float64), ('y', numpy.int32)]

In [54]:
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [55]:
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [56]:
sarr[0]

(1.5, 6)

In [58]:
sarr[0]['y']

6

## 嵌套 dtype 和多位字段

In [59]:
dtype = [('x', np.int64, 3), ('y', np.int32)]

In [60]:
arr = np.zeros(4, dtype=dtype)

In [61]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [62]:
arr[0]

([0, 0, 0], 0)

In [63]:
arr[0]['x']

array([0, 0, 0])

In [64]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]

In [69]:
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)

In [70]:
data

array([((1.0, 2.0), 5), ((3.0, 4.0), 6)], 
      dtype=[('x', [('a', '<f8'), ('b', '<f4')]), ('y', '<i4')])

In [71]:
data['x']

array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('a', '<f8'), ('b', '<f4')])

In [72]:
data['y']

array([5, 6], dtype=int32)

In [73]:
data['x']['a']

array([ 1.,  3.])

## 为什么要用结构化数组

## 结构化数组操作：numpy.lib.recfunctions

# 更多有关排序的话题

In [74]:
arr = randn(6)

In [75]:
arr

array([ 2.55816503, -0.80457866, -0.80219548, -1.00539019, -1.05661705,
       -2.75838518])

In [76]:
arr.sort()

In [77]:
arr

array([-2.75838518, -1.05661705, -1.00539019, -0.80457866, -0.80219548,
        2.55816503])

In [78]:
arr = randn(3, 5)

In [79]:
arr

array([[ 1.33438799,  1.31185688,  0.64144491,  0.72171933,  0.45286923],
       [ 1.1353733 ,  1.38839881, -0.71721531,  0.21322964, -0.54835024],
       [ 0.72847401, -1.1904733 , -1.07083602, -1.43799917,  0.02950219]])

In [80]:
arr[:, 0]

array([ 1.33438799,  1.1353733 ,  0.72847401])

In [81]:
arr[:, 0].sort()

In [83]:
arr[:, 0]

array([ 0.72847401,  1.1353733 ,  1.33438799])

In [82]:
arr

array([[ 0.72847401,  1.31185688,  0.64144491,  0.72171933,  0.45286923],
       [ 1.1353733 ,  1.38839881, -0.71721531,  0.21322964, -0.54835024],
       [ 1.33438799, -1.1904733 , -1.07083602, -1.43799917,  0.02950219]])

In [84]:
arr = randn(5)

In [85]:
arr

array([ 0.44896751, -2.47147295,  1.46546611,  0.27136008, -0.52851954])

In [86]:
np.sort(arr)

array([-2.47147295, -0.52851954,  0.27136008,  0.44896751,  1.46546611])

In [87]:
arr

array([ 0.44896751, -2.47147295,  1.46546611,  0.27136008, -0.52851954])

In [88]:
arr = randn(3, 5)

In [89]:
arr

array([[ 1.37218986, -0.80082777, -2.34490709,  1.70806455,  0.53160497],
       [-1.33628398,  1.75307557,  1.14798837, -1.17271609, -0.01567004],
       [ 0.32077722, -0.45836517,  1.15354699,  0.95163089, -0.64174206]])

In [90]:
arr.sort(axis=1)

In [91]:
arr

array([[-2.34490709, -0.80082777,  0.53160497,  1.37218986,  1.70806455],
       [-1.33628398, -1.17271609, -0.01567004,  1.14798837,  1.75307557],
       [-0.64174206, -0.45836517,  0.32077722,  0.95163089,  1.15354699]])

In [92]:
arr[::-1]

array([[-0.64174206, -0.45836517,  0.32077722,  0.95163089,  1.15354699],
       [-1.33628398, -1.17271609, -0.01567004,  1.14798837,  1.75307557],
       [-2.34490709, -0.80082777,  0.53160497,  1.37218986,  1.70806455]])

## 间接排序：argsort 和 lexsort

In [94]:
values = np.array([5, 0, 1, 3, 2])

In [95]:
indexer = values.argsort()

In [97]:
indexer

array([1, 2, 4, 3, 0])

In [100]:
values.argsort?

In [101]:
values[indexer]

array([0, 1, 2, 3, 5])

In [102]:
arr = randn(3, 5)

In [103]:
arr[0] = values

In [104]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.11569346,  0.82567286,  2.15440393,  0.71177593, -0.01999842],
       [-1.33888722,  0.28849909,  1.47327589, -0.13378365, -0.51191893]])

In [105]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.82567286,  2.15440393, -0.01999842,  0.71177593, -0.11569346],
       [ 0.28849909,  1.47327589, -0.51191893, -0.13378365, -1.33888722]])

In [107]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])

In [108]:
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [110]:
sorter = np.lexsort((first_name, last_name))

In [111]:
sorter

array([1, 2, 3, 0, 4])

In [114]:
zip(last_name[sorter], first_name[sorter])

In [115]:
zip?

## 其他排序算法

In [116]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])

In [117]:
key = np.array([2, 2, 1, 1, 1])

In [118]:
indexer = key.argsort(kind='mergesort')

In [119]:
indexer

array([2, 3, 4, 0, 1])

In [120]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='<U8')

## numpy.searchsorted

In [121]:
arr = np.array([0, 1, 7, 12, 15])

In [122]:
arr

array([ 0,  1,  7, 12, 15])

In [123]:
arr.searchsorted(9)

3

In [125]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [126]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])

In [127]:
arr.searchsorted([0, 1])

array([0, 3])

In [128]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [131]:
data = np.floor(np.random.uniform(0, 10000, size=50))

In [132]:
bins = np.array([0, 100, 1000, 5000, 10000])

In [133]:
data

array([  1.19900000e+03,   3.36500000e+03,   3.45000000e+03,
         5.47600000e+03,   7.04000000e+03,   7.76800000e+03,
         3.08300000e+03,   5.43200000e+03,   7.76600000e+03,
         9.19800000e+03,   2.57500000e+03,   5.28100000e+03,
         9.49800000e+03,   3.12400000e+03,   3.00000000e+00,
         1.50100000e+03,   8.09900000e+03,   6.70000000e+01,
         6.47700000e+03,   9.98200000e+03,   1.52800000e+03,
         1.37400000e+03,   8.79100000e+03,   6.10700000e+03,
         3.88400000e+03,   8.47400000e+03,   2.30000000e+01,
         8.83600000e+03,   8.46100000e+03,   7.09000000e+02,
         4.17500000e+03,   1.24400000e+03,   9.25200000e+03,
         2.10200000e+03,   1.40000000e+01,   3.38000000e+03,
         3.68100000e+03,   1.73300000e+03,   9.23300000e+03,
         1.67600000e+03,   1.63000000e+02,   1.95700000e+03,
         1.60500000e+03,   9.68100000e+03,   7.65000000e+02,
         8.49000000e+02,   7.21700000e+03,   7.93400000e+03,
         1.16700000e+03,

In [134]:
labels = bins.searchsorted(data)

In [135]:
labels

array([3, 3, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 1, 4, 4, 3, 3, 4,
       4, 3, 4, 1, 4, 4, 2, 3, 3, 4, 3, 1, 3, 3, 3, 4, 3, 2, 3, 3, 4, 2, 2,
       4, 4, 3, 3])

In [137]:
from pandas import Series

In [138]:
Series(data).groupby(labels).mean()

1      26.750000
2     621.500000
3    2436.714286
4    7904.904762
dtype: float64

In [139]:
np.digitize(data, bins)

array([3, 3, 3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 1, 3, 4, 1, 4, 4, 3, 3, 4,
       4, 3, 4, 1, 4, 4, 2, 3, 3, 4, 3, 1, 3, 3, 3, 4, 3, 2, 3, 3, 4, 2, 2,
       4, 4, 3, 3])